<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Active' => '',
    'Age Restriction' => '',
    'Author' => 'Автор',
    'Author ID' => '',
    'Avatar' => 'Аватар',
    'Banned' => '',
    'Birthday' => 'День рождения',
    'Category' => 'Категория',
    'Category ID' => '',
    'City ID' => '',
    'Comment' => 'Комментарий',
    'Created At' => '',
    'Created at' => 'Время создания',
    'Deleted' => '',
    'Description' => 'Описание',
    'Email' => '',
    'End' => '',
    'Firstname' => 'Имя',
    'Frequency' => 'Частота',
    'Gender' => 'Пол',
    'ID' => '',
    'Icon' => '',
    'Inactive' => '',
    'Is Free' => '',
    'Key' => 'Ключ',
    'Keywords' => 'Ключевые слова',
    'Last action at' => 'Активность',
    'Lastname' => 'Фамилия',
    'Link' => 'Ссылка',
    'Name' => 'Имя',
    'Organizer' => '',
    'Other' => 'Прочее',
    'Parent' => 'Родитель',
    'Password' => 'Пароль',
    'Place ID' => '',
    'Preview' => 'Анонс',
    'Published At' => '',
    'Published at' => 'Время публикации',
    'Remember me' => 'Запомнить меня',
    'Slug' => 'ЧПУ',
    'Sort index' => 'Индекс сортировки',
    'Start' => '',
    'Status' => 'Статус',
    'Tags' => 'Теги',
    'Text' => 'Текст',
    'Title' => 'Название',
    'Updated At' => '',
    'Updated at' => 'Время обновления',
    'Updater' => 'Обновивший',
    'Updater ID' => '',
    'Username' => 'Имя пользователя',
    'Username or email' => 'Имя пользователя или email',
    'Value' => 'Значение',
    'Website' => 'Веб-сайт',
    'Обложка' => 'Обложка',
];
